/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-11-15 08:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeCreate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/layout/sideNavi.jsp", Long.valueOf(1542268950317L));
    _jspx_dependants.put("/layout/head.jsp", Long.valueOf(1542269342615L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <!-- head 부분 -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>메인 페이지</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Fontastic Custom icon font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/fontastic.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\">\r\n");
      out.write("    <!-- jQuery Circle-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/grasp_mobile_progress_circle-1.0.0.min.css\">\r\n");
      out.write("    <!-- Custom Scrollbar-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/custom.css\">\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/img/favicon.ico\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("   \r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- Side Navbar -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"side-navbar\">\r\n");
      out.write("      <div class=\"side-navbar-wrapper\">\r\n");
      out.write("        <!-- Sidebar Header    -->\r\n");
      out.write("        <div class=\"sidenav-header d-flex align-items-center justify-content-center\">\r\n");
      out.write("          <!-- User Info-->\r\n");
      out.write("          <div class=\"sidenav-header-inner text-center\"><img src=\"/img/avatar-7.jpg\" alt=\"person\" class=\"img-fluid rounded-circle\">\r\n");
      out.write("            <h2 class=\"h5\">Nathan Andrews</h2><span>Web Developer</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Small Brand information, appears on minimized sidebar-->\r\n");
      out.write("          <div class=\"sidenav-header-logo\"><a href=\"/index.html\" class=\"brand-small text-center\"> <strong>B</strong><strong class=\"text-primary\">D</strong></a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Sidebar Navigation Menus-->\r\n");
      out.write("        <div class=\"main-menu\">\r\n");
      out.write("          <h5 class=\"sidenav-heading\">Main</h5>\r\n");
      out.write("          <ul id=\"side-main-menu\" class=\"side-menu list-unstyled\">                  \r\n");
      out.write("            <li><a href=\"/views/main.jsp\"> <i class=\"icon-home\"></i>Home                             </a></li>\r\n");
      out.write("            <li><a href=\"/forms.html\"> <i class=\"icon-form\"></i>Forms                             </a></li>\r\n");
      out.write("            <li><a href=\"/charts.html\"> <i class=\"fa fa-bar-chart\"></i>Charts                             </a></li>\r\n");
      out.write("            <li><a href=\"/tables.html\"> <i class=\"icon-grid\"></i>Tables                             </a></li>\r\n");
      out.write("            <li><a href=\"#boardDropDown\" aria-expanded=\"false\" data-toggle=\"collapse\"> <i class=\"icon-interface-windows\"></i>Board</a>\r\n");
      out.write("              <ul id=\"boardDropDown\" class=\"collapse list-unstyled \">\r\n");
      out.write("                <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"#\">기술공유</a></li>\r\n");
      out.write("                <li><a href=\"#\">기술지원</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"/login.html\"> <i class=\"icon-interface-windows\"></i>Login page                             </a></li>\r\n");
      out.write("            <li> <a href=\"#\"> <i class=\"icon-mail\"></i>Demo\r\n");
      out.write("                <div class=\"badge badge-warning\">6 New</div></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 어드민 페이지가 아닌경우 display none으로 변경 -->\r\n");
      out.write("        <div class=\"admin-menu\"  style=\"display:block;\">\r\n");
      out.write("          <h5 class=\"sidenav-heading\">Admin menu</h5>\r\n");
      out.write("          <ul id=\"side-admin-menu\" class=\"side-menu list-unstyled\"> \r\n");
      out.write("            <li> <a href=\"#\"> <i class=\"icon-screen\"> </i>회원 전체 정보 조회</a></li>\r\n");
      out.write("            <li> <a href=\"#\"> <i class=\"icon-flask\"> </i>회원 가입 승인</a></li>\r\n");
      out.write("                <div class=\"badge badge-info\">Special</div></a></li>\r\n");
      out.write("            <li> <a href=\"\"> <i class=\"icon-flask\"> </i>Demo</a></li>\r\n");
      out.write("            <li> <a href=\"\"> <i class=\"icon-picture\"> </i>Demo</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"page\">\r\n");
      out.write("      <!-- navbar-->\r\n");
      out.write("      <header class=\"header\">\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("          <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"navbar-holder d-flex align-items-center justify-content-between\">\r\n");
      out.write("              <div class=\"navbar-header\"><a id=\"toggle-btn\" href=\"#\" class=\"menu-btn\"><i class=\"icon-bars\"> </i></a><a href=\"index.html\" class=\"navbar-brand\">\r\n");
      out.write("                  <div class=\"brand-text d-none d-md-inline-block\"><span>Bootstrap </span><strong class=\"text-primary\">Dashboard</strong></div></a></div>\r\n");
      out.write("              <ul class=\"nav-menu list-unstyled d-flex flex-md-row align-items-md-center\">\r\n");
      out.write("                <!-- Notifications dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\"> <a id=\"notifications\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><i class=\"fa fa-bell\"></i><span class=\"badge badge-warning\">12</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"notifications\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-envelope\"></i>You have 6 new messages </div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-twitter\"></i>You have 2 followers</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-upload\"></i>Server Rebooted</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-twitter\"></i>You have 2 followers</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>10 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item all-notifications text-center\"> <strong> <i class=\"fa fa-bell\"></i>view all notifications                                            </strong></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Messages dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\"> <a id=\"messages\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><i class=\"fa fa-envelope\"></i><span class=\"badge badge-info\">10</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"notifications\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"img/avatar-1.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"img/avatar-2.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"img/avatar-3.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item all-notifications text-center\"> <strong> <i class=\"fa fa-envelope\"></i>Read all messages    </strong></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Languages dropdown    -->\r\n");
      out.write("                <li class=\"nav-item dropdown\"><a id=\"languages\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link language dropdown-toggle\"><img src=\"img/flags/16/GB.png\" alt=\"English\"><span class=\"d-none d-sm-inline-block\">English</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"languages\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> <img src=\"img/flags/16/DE.png\" alt=\"English\" class=\"mr-2\"><span>German</span></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> <img src=\"img/flags/16/FR.png\" alt=\"English\" class=\"mr-2\"><span>French                                                         </span></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Log out-->\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"login.html\" class=\"nav-link logout\"> <span class=\"d-none d-sm-inline-block\">Logout</span><i class=\"fa fa-sign-out\"></i></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("      <!-- Breadcrumb-->\r\n");
      out.write("      <div class=\"breadcrumb-holder\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <ul class=\"breadcrumb\">\r\n");
      out.write("            <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item active\">Forms       </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <section class=\"forms\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <!-- Page Header-->\r\n");
      out.write("          <header> \r\n");
      out.write("            <h1 class=\"h3 display\">Forms            </h1>\r\n");
      out.write("          </header>\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header d-flex align-items-center\">\r\n");
      out.write("                  <h4>Basic Form</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                  <form>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label>Email</label>\r\n");
      out.write("                      <input type=\"email\" placeholder=\"Email Address\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">       \r\n");
      out.write("                      <label>Password</label>\r\n");
      out.write("                      <input type=\"password\" placeholder=\"Password\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">       \r\n");
      out.write("                      <input type=\"submit\" value=\"Signin\" class=\"btn btn-primary\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header d-flex align-items-center\">\r\n");
      out.write("                  <h4>Horizontal Form</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                  <form class=\"form-horizontal\">\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2\">Email</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input id=\"inputHorizontalSuccess\" type=\"email\" placeholder=\"Email Address\" class=\"form-control form-control-success\"><small class=\"form-text\">Example help text that remains unchanged.</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2\">Password</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input id=\"inputHorizontalWarning\" type=\"password\" placeholder=\"Pasword\" class=\"form-control form-control-warning\"><small class=\"form-text\">Example help text that remains unchanged.</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">       \r\n");
      out.write("                      <div class=\"col-sm-10 offset-sm-2\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Signin\" class=\"btn btn-primary\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header d-flex align-items-center\">\r\n");
      out.write("                  <h4>Inline Form</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <form class=\"form-inline\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"inlineFormInput\" class=\"sr-only\">Name</label>\r\n");
      out.write("                      <input id=\"inlineFormInput\" type=\"text\" placeholder=\"Jane Doe\" class=\"mr-3 form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"inlineFormInputGroup\" class=\"sr-only\">Username</label>\r\n");
      out.write("                      <input id=\"inlineFormInputGroup\" type=\"text\" placeholder=\"Username\" class=\"mr-3 form-control form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <input type=\"submit\" value=\"Submit\" class=\"mr-3 btn btn-primary\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header d-flex align-items-center\">\r\n");
      out.write("                  <h4>Modal Form</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body text-center\">\r\n");
      out.write("                  <button type=\"button\" data-toggle=\"modal\" data-target=\"#myModal\" class=\"btn btn-primary\">Form in simple modal </button>\r\n");
      out.write("                  <!-- Modal-->\r\n");
      out.write("                  <div id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" class=\"modal fade text-left\">\r\n");
      out.write("                    <div role=\"document\" class=\"modal-dialog\">\r\n");
      out.write("                      <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                          <h5 id=\"exampleModalLabel\" class=\"modal-title\">Signin Modal</h5>\r\n");
      out.write("                          <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">×</span></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                          <p>Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                          <form>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <label>Email</label>\r\n");
      out.write("                              <input type=\"email\" placeholder=\"Email Address\" class=\"form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">       \r\n");
      out.write("                              <label>Password</label>\r\n");
      out.write("                              <input type=\"password\" placeholder=\"Password\" class=\"form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">       \r\n");
      out.write("                              <input type=\"submit\" value=\"Signin\" class=\"btn btn-primary\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                          <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-secondary\">Close</button>\r\n");
      out.write("                          <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header d-flex align-items-center\">\r\n");
      out.write("                  <h4>All form elements</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <form class=\"form-horizontal\">\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Normal</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Help text</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\"><span class=\"text-small text-gray help-block-none\">A block of help text that breaks onto a new line and may extend beyond one line.</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Password</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Placeholder</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"placeholder\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-lg-2 form-control-label\">Disabled</label>\r\n");
      out.write("                      <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"text\" disabled=\"\" placeholder=\"Disabled input here...\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Checkboxes and radios <br><small class=\"text-primary\">Normal Bootstrap elements</small></label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <input id=\"option\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                          <label for=\"option\">Option one is this and that—be sure to include why it's great</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <input id=\"optionsRadios1\" type=\"radio\" checked=\"\" value=\"option1\" name=\"optionsRadios\">\r\n");
      out.write("                          <label for=\"optionsRadios1\">Option one is this and that be sure to include why it's great</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <input id=\"optionsRadios2\" type=\"radio\" value=\"option2\" name=\"optionsRadios\">\r\n");
      out.write("                          <label for=\"optionsRadios2\">Option two can be something else and selecting it will deselect option one</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Inline checkboxes</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <label class=\"checkbox-inline\">\r\n");
      out.write("                          <input id=\"inlineCheckbox1\" type=\"checkbox\" value=\"option1\"> a\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"checkbox-inline\">\r\n");
      out.write("                          <input id=\"inlineCheckbox2\" type=\"checkbox\" value=\"option2\"> b\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"checkbox-inline\">\r\n");
      out.write("                          <input id=\"inlineCheckbox3\" type=\"checkbox\" value=\"option3\"> c\r\n");
      out.write("                        </label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Checkboxes &amp; radios <br><small class=\"text-primary\">Custom elements</small></label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"checkboxCustom1\" type=\"checkbox\" value=\"\" class=\"form-control-custom\">\r\n");
      out.write("                          <label for=\"checkboxCustom1\">Option one</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"checkboxCustom2\" type=\"checkbox\" value=\"\" checked=\"\" class=\"form-control-custom\">\r\n");
      out.write("                          <label for=\"checkboxCustom2\">Option two checked</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"checkboxCustom\" type=\"checkbox\" value=\"\" disabled=\"\" checked=\"\" class=\"form-control-custom\">\r\n");
      out.write("                          <label for=\"checkboxCustom\">Option three checked and disabled</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"checkboxCustom3\" type=\"checkbox\" value=\"\" disabled=\"\" class=\"form-control-custom\">\r\n");
      out.write("                          <label for=\"checkboxCustom3\">Option four disabled</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"radioCustom1\" type=\"radio\" value=\"option1\" name=\"a\" class=\"form-control-custom radio-custom\">\r\n");
      out.write("                          <label for=\"radioCustom1\">Option one</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"radioCustom2\" type=\"radio\" checked=\"\" value=\"option2\" name=\"a\" class=\"form-control-custom radio-custom\">\r\n");
      out.write("                          <label for=\"radioCustom2\">Option two checked</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"radioCustom3\" type=\"radio\" disabled=\"\" checked=\"\" value=\"option2\" class=\"form-control-custom radio-custom\">\r\n");
      out.write("                          <label for=\"radioCustom3\">Option three checked and disabled</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"i-checks\">\r\n");
      out.write("                          <input id=\"radioCustom4\" type=\"radio\" disabled=\"\" name=\"a\" class=\"form-control-custom radio-custom\">\r\n");
      out.write("                          <label for=\"radioCustom4\">Option four disabled</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Select</label>\r\n");
      out.write("                      <div class=\"col-sm-10 mb-3\">\r\n");
      out.write("                        <select name=\"account\" class=\"form-control\">\r\n");
      out.write("                          <option>option 1</option>\r\n");
      out.write("                          <option>option 2</option>\r\n");
      out.write("                          <option>option 3</option>\r\n");
      out.write("                          <option>option 4</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-sm-10 offset-sm-2\">\r\n");
      out.write("                        <select multiple=\"\" class=\"form-control\">\r\n");
      out.write("                          <option>option 1</option>\r\n");
      out.write("                          <option>option 2</option>\r\n");
      out.write("                          <option>option 3</option>\r\n");
      out.write("                          <option>option 4</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row has-success\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Input with success</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control is-valid\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row has-danger\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Input with error</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control is-invalid\">\r\n");
      out.write("                        <div class=\"invalid-feedback\">Please provide your name.</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Control sizing</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <input type=\"text\" placeholder=\".input-lg\" class=\"form-control form-control-lg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <input type=\"text\" placeholder=\"Default input\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <input type=\"text\" placeholder=\".input-sm\" class=\"form-control form-control-sm\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Column sizing</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-md-2\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\".col-md-2\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-3\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\".col-md-3\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-4\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\".col-md-4\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"> </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Material Inputs</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"form-group-material\">\r\n");
      out.write("                          <input id=\"register-username\" type=\"text\" name=\"registerUsername\" required class=\"input-material\">\r\n");
      out.write("                          <label for=\"register-username\" class=\"label-material\">Username</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group-material\">\r\n");
      out.write("                          <input id=\"register-email\" type=\"email\" name=\"registerEmail\" required class=\"input-material\">\r\n");
      out.write("                          <label for=\"register-email\" class=\"label-material\">Email Address      </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group-material\">\r\n");
      out.write("                          <input id=\"register-password\" type=\"password\" name=\"registerPassword\" required class=\"input-material\">\r\n");
      out.write("                          <label for=\"register-password\" class=\"label-material\">Password                                                      </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Input groups</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\"><span class=\"input-group-text\">@</span></div>\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Username\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                            <div class=\"input-group-append\"><span class=\"input-group-text\">.00</span></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\"><span class=\"input-group-text\">$</span></div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                            <div class=\"input-group-append\"><span class=\"input-group-text\">.00</span></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                              <div class=\"input-group-text\">\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                              <div class=\"input-group-text\">\r\n");
      out.write("                                <input type=\"radio\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">Button addons</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                              <button type=\"button\" class=\"btn btn-primary\">Go!</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                            <div class=\"input-group-append\">\r\n");
      out.write("                              <button type=\"button\" class=\"btn btn-primary\">Go!</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <label class=\"col-sm-2 form-control-label\">With dropdowns</label>\r\n");
      out.write("                      <div class=\"col-sm-10\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <div class=\"input-group-prepend\">\r\n");
      out.write("                            <button data-toggle=\"dropdown\" type=\"button\" class=\"btn btn-outline-secondary dropdown-toggle\">Action <span class=\"caret\"></span></button>\r\n");
      out.write("                            <div class=\"dropdown-menu\"><a href=\"#\" class=\"dropdown-item\">Action</a><a href=\"#\" class=\"dropdown-item\">Another action</a><a href=\"#\" class=\"dropdown-item\">Something else here</a>\r\n");
      out.write("                              <div class=\"dropdown-divider\"></div><a href=\"#\" class=\"dropdown-item\">Separated link</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                      <div class=\"col-sm-4 offset-sm-2\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-secondary\">Cancel</button>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-6\">\r\n");
      out.write("              <p>Your company &copy; 2017-2019</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6 text-right\">\r\n");
      out.write("              <p>Design by <a href=\"https://bootstrapious.com\" class=\"external\">Bootstrapious</a></p>\r\n");
      out.write("              <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- JavaScript files-->\r\n");
      out.write("    <script src=\"/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/grasp_mobile_progress_circle-1.0.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery-validation/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <!-- Main File-->\r\n");
      out.write("    <script src=\"/js/front.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
