/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-04 11:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1542254324508L));
    _jspx_dependants.put("jar:file:/D:/web_workspace_sol/sol/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/layout/head.jsp", Long.valueOf(1543892283752L));
    _jspx_dependants.put("/layout/javaScriptFile.jsp", Long.valueOf(1543897146044L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write(" \t \t\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>메인 페이지</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Fontastic Custom icon font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/fontastic.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\">\r\n");
      out.write("    <!-- jQuery Circle-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/grasp_mobile_progress_circle-1.0.0.min.css\">\r\n");
      out.write("    <!-- Custom Scrollbar-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/custom.css\">\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/img/logo.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"page login-page\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"form-outer text-center d-flex align-items-center\">\r\n");
      out.write("          <div class=\"form-inner\">\r\n");
      out.write("            <div class=\"logo text-uppercase\"><strong class=\"text-primary\">회원가입</strong></div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <pre><p>              저희 솔루션의 관계자만 가입이 가능합니다.              </p></pre>\r\n");
      out.write("            <form action=\"/register.do\" method=\"post\" class=\"text-left form-validate\">\r\n");
      out.write("            \r\n");
      out.write("               <div class=\"dropdown dropdown-validate\">\r\n");
      out.write("    \t\t \t \t<button id=\"selectCompany\" type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("      \t\t\t\t \t회사 종류 선택\r\n");
      out.write("    \t\t\t\t</button>\r\n");
      out.write("    \t\t\t\t<div id=\"companyMessage\" style=\"font-size:8px\"></div>    \t\t\t\r\n");
      out.write("    \t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("      \t\t\t\t\t<a id=\"selectPartner\" class=\"dropdown-item\" href=\"#\">협력사</a>\r\n");
      out.write("      \t\t\t\t\t<a id=\"selectManufacturer\" class=\"dropdown-item\" href=\"#\">제조사</a>\t      \t\t\t\r\n");
      out.write("\t    \t\t\t</div>\t    \t\r\n");
      out.write("  \t\t\t  </div>\r\n");
      out.write("  \t\t\t  \r\n");
      out.write("  \t\t\t  <div id=\"enterCompany\" class=\"form-group-material\"  style=\"display:none\">\r\n");
      out.write("               \t<input id=\"register-company\" type=\"text\" name=\"registerCompany\" required data-msg=\"Please enter your company\" class=\"input-material\">\r\n");
      out.write("               \t<label for=\"register-company\" class=\"label-material\">Company Name </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <br><br>\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"form-group-material\">\r\n");
      out.write("                <input id=\"register-username\" type=\"text\" name=\"registerUsername\" required data-msg=\"Please enter your username\" class=\"input-material\">\r\n");
      out.write("                <label for=\"register-username\" class=\"label-material\">User Name</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group-material\">\r\n");
      out.write("                <input id=\"register-email\" type=\"text\" name=\"registerEmail\" required data-msg=\"Please enter a valid email address\" class=\"input-material\">\r\n");
      out.write("                <label for=\"register-email\" class=\"label-material\">Email Address      </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group-material\">\r\n");
      out.write("                <input id=\"register-password\" type=\"password\" name=\"registerPassword\" required data-msg=\"Please enter your password\" class=\"input-material\">\r\n");
      out.write("                <label for=\"register-password\" class=\"label-material\">Password        </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group-material\">\r\n");
      out.write("                <input id=\"register-phone\" type=\"text\" name=\"registerPhone\" required data-msg=\"Please enter your phone number\" class=\"input-material\">\r\n");
      out.write("                <label for=\"register-phone\" class=\"label-material\">Phone        </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group-material\">\r\n");
      out.write("                <input id=\"register-address\" type=\"text\" name=\"registerAddress\" required data-msg=\"Please enter your address\" class=\"input-material\">\r\n");
      out.write("                <label for=\"register-address\" class=\"label-material\">Address        </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group terms-conditions text-center\">\r\n");
      out.write("                <input id=\"register-agree\" name=\"registerAgree\" type=\"checkbox\" required value=\"1\" data-msg=\"Your agreement is required\" class=\"form-control-custom\">\r\n");
      out.write("                <label for=\"register-agree\">I agree with the terms and policy</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group text-center\">\r\n");
      out.write("                <input id=\"register\" type=\"submit\" onclick=\"return check();\" value=\"Register\" class=\"btn btn-primary\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </form><small>Already have an account? </small><a href=\"/index.jsp\" class=\"signup\">Login</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"copyrights text-center\">\r\n");
      out.write("            <p>Design by <a href=\"https://bootstrapious.com\" class=\"external\">Bootstrapious</a></p>\r\n");
      out.write("            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- JavaScript files-->\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \t<script src=\"/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/grasp_mobile_progress_circle-1.0.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery-validation/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/charts-home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \t<script>\r\n");
      out.write("    function check() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar selectComapany = $(\"#selectCompany\").html();\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(selectComapany.length);\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tif(selectComapany.length==3){\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}else{\t\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#companyMessage\").css(\"color\",\"red\");\r\n");
      out.write("\t\t\t$(\"#companyMessage\").html(\"회사 종류를 선택해주세요\");\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  \t</script>  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("    <!-- Main File-->\r\n");
      out.write("    <script src=\"/js/front.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
