/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-09 19:13:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1544280365700L));
    _jspx_dependants.put("jar:file:/C:/Users/cih46/Desktop/최성현/kh정보교육원/sol/web_workspace_sol/sol/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/layout/header.jsp", Long.valueOf(1544280350551L));
    _jspx_dependants.put("/layout/head.jsp", Long.valueOf(1544382273389L));
    _jspx_dependants.put("/layout/javaScriptFile.jsp", Long.valueOf(1544280350602L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write(" \t \t\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>메인 페이지</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Fontastic Custom icon font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/fontastic.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\">\r\n");
      out.write("    <!-- jQuery Circle-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/grasp_mobile_progress_circle-1.0.0.min.css\">\r\n");
      out.write("    <!-- Custom Scrollbar-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/custom.css\">\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/img/logo.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body> \r\n");
      out.write("    <div class=\"page\">\r\n");
      out.write("      <!-- navbar-->\r\n");
      out.write("      ");
      out.write(" \t<header class=\"header\">\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("          <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"navbar-holder d-flex align-items-center justify-content-between\">\r\n");
      out.write("              <div class=\"navbar-header\"><a id=\"toggle-btn\" href=\"#\" class=\"menu-btn\"><i class=\"icon-bars\"> </i></a><a href=\"/views/main.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                  <div class=\"brand-text d-none d-md-inline-block\"><span>Technical</span><strong class=\"text-primary\">Support</strong></div></a></div>\r\n");
      out.write("              <ul class=\"nav-menu list-unstyled d-flex flex-md-row align-items-md-center\">\r\n");
      out.write("                <!-- Notifications dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\"> <a id=\"notifications\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><i class=\"fa fa-bell\"></i><span class=\"badge badge-warning\">12</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"notifications\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-envelope\"></i>You have 6 new messages </div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-twitter\"></i>You have 2 followers</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-upload\"></i>Server Rebooted</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>4 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> \r\n");
      out.write("                        <div class=\"notification d-flex justify-content-between\">\r\n");
      out.write("                          <div class=\"notification-content\"><i class=\"fa fa-twitter\"></i>You have 2 followers</div>\r\n");
      out.write("                          <div class=\"notification-time\"><small>10 minutes ago</small></div>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item all-notifications text-center\"> <strong> <i class=\"fa fa-bell\"></i>view all notifications                                            </strong></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Messages dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\"> <a id=\"messages\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><i class=\"fa fa-envelope\"></i><span class=\"badge badge-info\">10</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"notifications\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"/img/avatar-1.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"/img/avatar-2.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item d-flex\"> \r\n");
      out.write("                        <div class=\"msg-profile\"> <img src=\"/img/avatar-3.jpg\" alt=\"...\" class=\"img-fluid rounded-circle\"></div>\r\n");
      out.write("                        <div class=\"msg-body\">\r\n");
      out.write("                          <h3 class=\"h5\">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item all-notifications text-center\"> <strong> <i class=\"fa fa-envelope\"></i>Read all messages    </strong></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Languages dropdown    -->\r\n");
      out.write("                <li class=\"nav-item dropdown\"><a id=\"languages\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link language dropdown-toggle\"><img src=\"/img/flags/16/GB.png\" alt=\"English\"><span class=\"d-none d-sm-inline-block\">English</span></a>\r\n");
      out.write("                  <ul aria-labelledby=\"languages\" class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> <img src=\"img/flags/16/DE.png\" alt=\"English\" class=\"mr-2\"><span>German</span></a></li>\r\n");
      out.write("                    <li><a rel=\"nofollow\" href=\"#\" class=\"dropdown-item\"> <img src=\"img/flags/16/FR.png\" alt=\"English\" class=\"mr-2\"><span>French                                                         </span></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Log out-->\r\n");
      out.write("                <li class=\"nav-item\"><a href=\"/logout.do\" class=\"nav-link logout\"> <span class=\"d-none d-sm-inline-block\">Logout</span><i class=\"fa fa-sign-out\"></i></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write(" \t</header>");
      out.write("\r\n");
      out.write("    <div class=\"page login-page\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"form-outer text-center d-flex align-items-center\">\r\n");
      out.write("          <div class=\"form-inner\">\r\n");
      out.write("            <div class=\"logo text-uppercase\"><span>&nbsp;&nbsp;&nbsp;Login&nbsp;</span><strong class=\"text-primary\">&nbsp;check\t&nbsp;&nbsp;&nbsp;</strong></div>\r\n");
      out.write("            <p>로그인 후 이용해주세요<br> 세션이 만료되었거나 로그인하지 않았습니다.</p>\r\n");
      out.write("                       \r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group text-center\"><a href=\"/index.jsp\" class=\"btn btn-primary\" value=\"\">로그인 페이지로 이동</a>\r\n");
      out.write("                <!-- This should be submit button but I replaced it with <a> for demo purposes-->\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"copyrights text-center\">\r\n");
      out.write("            <p>Design by <a href=\"https://bootstrapious.com\" class=\"external\">Bootstrapious</a></p>\r\n");
      out.write("            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("    <!-- JavaScript files-->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \t<script src=\"/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/grasp_mobile_progress_circle-1.0.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/jquery-validation/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <script src=\"/js/charts-home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- Main File-->\r\n");
      out.write("    <script src=\"/js/front.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
